### PR TITLE
now globally setting box sizing border box and a mid screen size where w...

### PR DESCRIPTION
**Pull request by ScottDowne**
...e can fit float left instead of stacking the scll script pages

### CODE REVIEW

**Comment by ScottDowne** [comment]
I got it all working with better box sizing. Previously we had box sizing set as we needed it, but turns out everything could use it now except the input box, so I fixed the input box and now we can set our box sizing globally.

I also noticed we could float the larger mid screen size call script instead of stacking it. This also happens to be my primary desktop screen size so I personally wanted this fixed.

**Comment by alicoding** [comment]
You need to fix the button now since it is too big 
screen shot 2015-02-07 at 20 30 30

**Comment by alicoding** [comment]
This looks really good now except that two problems that I've listed above and this is will be good to merge.

**Comment by ScottDowne** [comment]
Updated

**Pull request merged**
