### PR TITLE
Add LICENSE MIT

### LINKED ISSUE #74: License?
Could you add a license file, eg AGPL v 3, or GPL v3, etc.

### PR DESCRIPTION
**Pull request by alicoding**
Closes #74

### CODE REVIEW

**Comment by alicoding** [comment]
@ScottDowne R?

**Comment by alicoding** [comment]
@simonwex is this the right LICENSE file? What do you think?

**Comment by ScottDowne** [comment]
I think @simonwex should review this one.

**Comment by simonwex** [comment]
This is the MPLv2, not MIT. MPLv2 *is* what we should license our stuff as by default, though.

R+

**Pull request merged**
