### PR TITLE
layout of page 1 changes

### PR DESCRIPTION
**Pull request by ScottDowne**
The desktop page 1 view is not aligned correctly with the redpen.

This patch fixes that.

### CODE REVIEW

**Comment by simonwex** [comment]
Which issues should this PR fix, @ScottDowne?

**Comment by alicoding** [comment]
@simonwex this patch is basically cleaning up based on the Redpen, so I don't think there is any one specifically

**Comment by ScottDowne** [comment]
I never filed this, it's just an issue in a pull.

**Comment by ScottDowne** [comment]
Going to throw this to Ali for review if that works for everyone.

**Comment by alicoding** [comment]
r+

**Pull request merged**
